---
- name: build java project
  hosts: maven
  become: yes

  tasks:
  - name: Ensure default-jdk is presented
    apt:
      name: default-jdk
      state: present

  - name: Ensure maven is presented
    apt:
      name: maven
      state: present

  - name: Ensure project from git is cloned
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello
      dest: /home/boxfuse

  - name: Build project
    shell: mvn package
    args:
      chdir: /home/boxfuse

  - name: Ensure hello.war is downloaded
    fetch:
      src: /home/boxfuse/target/hello-1.0.war
      dest: /tmp

- name: deploy application
  hosts: web
  become: yes

  tasks:
    - name: Ensure tomcat8 is presented
      apt:
        name: tomcat8
        state: present

    - name: Ensure hello.war is uploaded
      copy:
        src: /tmp/52.58.135.180/home/boxfuse/target
        dest: /var/lib/tomcat8/webapps

    - name: Ensure tomcat8 service is restarted
      service:
        name: tomcat8
        state: restarted